[package]
name = "rust-workflow-engine"
version = "0.1.0"
authors = ["Cody Lambert <codylambertdev@gmail.com>"]
edition = "2021"
license = "MIT"  # or "Apache-2.0"
description = "A multi-threaded, asynchronous workflow engine for Rust."
repository = "https://github.com/romanguy13/rust-workflow-engine"

[dependencies]
async-trait = "0.1"
tokio = { version = "1", features = ["full"] }
sqlx = { version = "0.6", features = ["sqlite", "runtime-tokio-native-tls", "macros"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
env_logger = "0.9"
# sqlx-cli = { version = "0.6", features = ["sqlite"] }

[dev-dependencies]
tokio-test = "0.4"
